export default {
  USER_TYPE: 0,
  PROCESS_STATE: {},
  PROFIL_INFO: {},
  INTERNET: true,
  worker: {downloadContent: {}, modalcontent: ''},
  IMAGES: {
    SPLASH: require('../assets/splash.png'),
    LO_SPLASH: require('../assets/lo_splash.png'),
    LOGO: require('../Images/logo.png'),
  },
  COLORS: {
    primary: '#fd7e14',
    secondary: '#204b9bff',
    primary_pure: '#f4440cff',
    accent: '#50c878',
    background: '#f7f9fb',
    co_gris: '#dbe3de',
    pur_green: '#445500',
    light_green: '#d7f4e3',
    light_blue: '#29B2FE',
    black: '#000000',
    white: '#ffffff',
    aliceblue: '#fa9bd921',
    truealiceblue: '#F0F8FF',
    purple: '#9C27B0',
    blue: '#2196F3',
    teal: '#009688',
    green: '#4CAF50',
    orange: '#FF9800',
    grey: '#9E9E9E',
    blue_grey: '#607D8B',
    light_grey: '#eceff5',
    blue_dark: '#23233cff',
    cerulean: '#007791',
    arsenic: '#393f4a',
    arsenic2: '#535e72ff',
  },
  STRINGS: {
    welcome: 'Bienvenue !',
    get_started: 'commençons au tout debut !',
    save: 'enrégistrés',
    checked: 'validés',
    gain: 'gains',
    rejected: 'rejetés',
    checkout: 'Encaisser',
    signout: 'Déconnecter',
    newHere: 'Vous êtes nouveau ici ?',
    alreadyRegistered: 'Vous avez déjà un compte ? ',
    translate: 'Traduire',
    password_forgot: 'mot de passe oublié ?',
    players: 'Joueurs en compétition',
    small_phone: 'Numéro de Télephone invalide (entrez au moins 8 caractères)',
    small_code: 'Code invalide (entrez au moins 5 caractères)',
    small_username: "nom d'itulisateur invalid (entrez au moins 5 caractères)",
    terms_declaration: 'En utilisant nos services, vous acceptez nos ',
    register: 'Inscrivez Vous !',
    and: 'et',
    students: 'Elèves',
    connect: 'Se Connecter',
    connection: 'Connexion',
    Ocurred_error: 'An error occured',
    inscription: 'Inscription',
    firstname: 'Nom',
    lastname: 'prénom',
    username: "Nom d'utilisateur",
    mail: 'Addresse E-mail',
    phone: 'Numéro de Téléphone',
    address: 'Addresse',
    language: 'Langue',
    Profil: 'Profil',
    to: 'A',
    validate: 'Valider',
    state: 'Etat',
    cancel: 'Annuler',
    age: 'Age',
    validated: 'Validé',
    logout: 'Déconnexion',
    About: 'A Propos',
    no_internet: '🛸 Pas de connexion Internet !',
    categories: 'Catégories',
    home: 'Accueil',
    unknow_error: 'Une petite eurreur est survenu 😞',
    description: 'Description',
    will_learn: 'Ce que vous apprendrez',
    total_participants: 'Nombre total de participants',
    search: 'Rechercher',
    hello: 'Bienvenu',
    terminated: 'terminés',
    other: 'autre',
    total: 'Total',
    sur_deconnect: 'Voulez-vous déconnecter de Sedami ?',
    start_download: 'début Télechargement',
    confirm_download: 'Taille du Télechargemen : ',
    empty_notes: 'Aucune notes',
    likes_courses: 'Listes de Favoris !',
    explore: 'Explorer',
    check_con_retry:
      'Erreur de telechargement . verifiez votre connexion et reésayez',
    sucess_Update: 'Mise à jour reuissi',
  },
};
